// <auto-generated />
using System;
using ClimateGuard.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClimateGuard.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260822030138_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClimateGuard.Domain.Entities.Alert", b =>
                {
                    b.Property<long>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AlertId"));

                    b.Property<byte>("AlertSeverityId")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<byte?>("PhenomenonTypeId")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResolvedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("SensorId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TriggerValue")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("AlertId");

                    b.HasIndex("AlertSeverityId");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_Alerts_CreatedAt");

                    b.HasIndex("PhenomenonTypeId");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("IX_Alerts_SensorId");

                    b.ToTable("Alerts", "dbo");
                });

            modelBuilder.Entity("ClimateGuard.Domain.Entities.AlertSeverity", b =>
                {
                    b.Property<byte>("AlertSeverityId")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AlertSeverityId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AlertSeverities", "dbo");
                });

            modelBuilder.Entity("ClimateGuard.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<int>("AuditLogEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogEntryId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EntityAffected")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Timestamp")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AuditLogEntryId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogEntries", "dbo");
                });

            modelBuilder.Entity("ClimateGuard.Domain.Entities.Community", b =>
                {
                    b.Property<int>("CommunityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommunityId"));

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Region")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("CommunityId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Communities", "dbo");
                });

            modelBuilder.Entity("ClimateGuard.Domain.Entities.PhenomenonType", b =>
                {
                    b.Property<byte>("PhenomenonTypeId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PhenomenonTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PhenomenonTypes", "dbo");
                });

            modelBuilder.Entity("ClimateGuard.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReplacedByTokenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "dbo");
                });

            modelBuilder.Entity("ClimateGuard.Domain.Entities.Role", b =>
                {
                    b.Property<byte>("RoleId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", "dbo");
                });

            modelBuilder.Entity("ClimateGuard.Domain.Entities.Sensor", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SensorId"));

                    b.Property<int>("CommunityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("LastValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("SensorTypeId")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SensorId");

                    b.HasIndex("CommunityId");

                    b.HasIndex("SensorTypeId");

                    b.ToTable("Sensors", "dbo");
                });

            modelBuilder.Entity("ClimateGuard.Domain.Entities.SensorReading", b =>
                {
                    b.Property<long>("SensorReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SensorReadingId"));

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Timestamp")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("SensorReadingId");

                    b.HasIndex("SensorId", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_SensorReadings_SensorId_Timestamp");

                    b.ToTable("SensorReadings", "dbo");
                });

            modelBuilder.Entity("ClimateGuard.Domain.Entities.SensorType", b =>
                {
                    b.Property<byte>("SensorTypeId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("SensorTypeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SensorTypes", "dbo");
                });

            modelBuilder.Entity("ClimateGuard.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<byte>("RoleId")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("ClimateGuard.Domain.Entities.Alert", b =>
                {
                    b.HasOne("ClimateGuard.Domain.Entities.AlertSeverity", "AlertSeverity")
                        .WithMany("Alerts")
                        .HasForeignKey("AlertSeverityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Alerts_AlertSeverities");

                    b.HasOne("ClimateGuard.Domain.Entities.PhenomenonType", "PhenomenonType")
                        .WithMany("Alerts")
                        .HasForeignKey("PhenomenonTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Alerts_PhenomenonTypes");

                    b.HasOne("ClimateGuard.Domain.Entities.User", "ResolvedByUser")
                        .WithMany("ResolvedAlerts")
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Alerts_Users_ResolvedBy");

                    b.HasOne("ClimateGuard.Domain.Entities.Sensor", "Sensor")
                        .WithMany("Alerts")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Alerts_Sensors");

                    b.Navigation("AlertSeverity");

                    b.Navigation("PhenomenonType");

                    b.Navigation("ResolvedByUser");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("ClimateGuard.Domain.Entities.AuditLogEntry", b =>
                {
                    b.HasOne("ClimateGuard.Domain.Entities.User", "User")
                        .WithMany("AuditLogEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AuditLogEntries_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClimateGuard.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ClimateGuard.Domain.Entities.RefreshToken", "ReplacedByToken")
                        .WithMany("PreviousTokens")
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_RefreshTokens_ReplacedBy");

                    b.HasOne("ClimateGuard.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_Users");

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClimateGuard.Domain.Entities.Sensor", b =>
                {
                    b.HasOne("ClimateGuard.Domain.Entities.Community", "Community")
                        .WithMany("Sensors")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Sensors_Communities");

                    b.HasOne("ClimateGuard.Domain.Entities.SensorType", "SensorType")
                        .WithMany("Sensors")
                        .HasForeignKey("SensorTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Sensors_SensorTypes");

                    b.Navigation("Community");

                    b.Navigation("SensorType");
                });

            modelBuilder.Entity("ClimateGuard.Domain.Entities.SensorReading", b =>
                {
                    b.HasOne("ClimateGuard.Domain.Entities.Sensor", "Sensor")
                        .WithMany("Readings")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_SensorReadings_Sensors");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("ClimateGuard.Domain.Entities.User", b =>
                {
                    b.HasOne("ClimateGuard.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ClimateGuard.Domain.Entities.AlertSeverity", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("ClimateGuard.Domain.Entities.Community", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("ClimateGuard.Domain.Entities.PhenomenonType", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("ClimateGuard.Domain.Entities.RefreshToken", b =>
                {
                    b.Navigation("PreviousTokens");
                });

            modelBuilder.Entity("ClimateGuard.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ClimateGuard.Domain.Entities.Sensor", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Readings");
                });

            modelBuilder.Entity("ClimateGuard.Domain.Entities.SensorType", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("ClimateGuard.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogEntries");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ResolvedAlerts");
                });
#pragma warning restore 612, 618
        }
    }
}
